services:
  frontend:
    image: ghcr.io/robinnogues/my-cv-frontend:latest
    container_name: cv_frontend
    restart: unless-stopped

  backend:
    image: ghcr.io/robinnogues/my-cv-backend:latest
    container_name: cv_backend
    restart: unless-stopped
    env_file:
      - ./my-cv-backend/.env

  reverse-proxy:
    image: ghcr.io/robinnogues/my-cv-reverse-proxy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot_www:/var/www/certbot:ro           # challenge ACME
      - letsencrypt_data:/etc/letsencrypt:ro      # certificats
    depends_on:
      - frontend
      - backend
    container_name: cv_reverse_proxy
    restart: unless-stopped
    environment:
      - NGINX_HOST=robin-nogues.com
      - SSL_CERTIFICATE_PATH=/etc/letsencrypt/live/robin-nogues.com/fullchain.pem
      - SSL_CERTIFICATE_KEY_PATH=/etc/letsencrypt/live/robin-nogues.com/privkey.pem

  certbot:
    image: certbot/certbot
    container_name: cv_certbot
    volumes:
      - certbot_www:/var/www/certbot:rw
      - letsencrypt_data:/etc/letsencrypt:rw
  # in crontab:
  # 17 4 * * * cd /home/rnogues/my-cv && /usr/bin/docker compose run --rm certbot renew --quiet && /usr/bin/docker kill --signal=SIGHUP cv_reverse_proxy >> /home/rnogues/my-cv/cron-certbot.log 2>&1

volumes:
  certbot_www:
  letsencrypt_data:
