services:
  frontend:
    image: ghcr.io/robinnogues/my-cv-frontend:latest
    container_name: cv_frontend
    restart: unless-stopped

  backend:
    image: ghcr.io/robinnogues/my-cv-backend:latest
    container_name: cv_backend
    restart: unless-stopped
    env_file:
      - ./my-cv-backend/.env

  reverse-proxy:
    image: ghcr.io/robinnogues/my-cv-reverse-proxy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot_www:/var/www/certbot:ro # challenge ACME
      - letsencrypt_data:/etc/letsencrypt:ro # certificats
      - nginx_logs:/var/log/nginx
      - goaccess_report:/var/www/goaccess:ro
    depends_on:
      - frontend
      - backend
    container_name: cv_reverse_proxy
    restart: unless-stopped
    environment:
      - NGINX_HOST=robin-nogues.com
      - SSL_CERTIFICATE_PATH=/etc/letsencrypt/live/robin-nogues.com/fullchain.pem
      - SSL_CERTIFICATE_KEY_PATH=/etc/letsencrypt/live/robin-nogues.com/privkey.pem

  certbot:
    image: certbot/certbot
    container_name: cv_certbot
    volumes:
      - certbot_www:/var/www/certbot:rw
      - letsencrypt_data:/etc/letsencrypt:rw
    depends_on:
      - reverse-proxy

  goaccess:
    image: allinurl/goaccess
    container_name: cv_goaccess
    restart: unless-stopped
    depends_on:
      - reverse-proxy
    volumes:
      - nginx_logs:/srv/logs:ro
      - goaccess_report:/srv/report
    command: /srv/logs/access_file.log -o /srv/report/index.html --log-format=COMBINED --real-time-html --ws-url=wss://robin-nogues.com:443/goaccess-ws --origin=https://robin-nogues.com --anonymize-ip

volumes:
  certbot_www:
  letsencrypt_data:
  nginx_logs:
  goaccess_report:
