services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: cv_frontend
    restart: unless-stopped

networks:
  my_cv_network:
    external: true
