# GoAccess Configuration

# Log Format
log-format COMBINED

# Real-time HTML output
real-time-html true

# Privacy
anonymize-ip true

# Filters
ignore-crawlers true

# Static Files Filters
static-file .css
static-file .js
static-file .jpg
static-file .jpeg
static-file .png
static-file .gif
static-file .ico
static-file .svg
static-file .webp
static-file .woff
static-file .woff2
static-file .ttf
static-file .eot
static-file .map
static-file .json
static-file .webmanifest
