services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: cv_backend
    restart: unless-stopped
    env_file:
      - .env

networks:
  my_cv_network:
    driver: bridge
